version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      JWT_SECRET: your_very_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
